package com.paynote.app

import kotlin.random.Random

data class NativePlanTemplate(
    val body: String,
    val tier: Int
)

object PeriodicPlanFallbackTemplates {
    private val advisor = listOf(
        NativePlanTemplate("Ăn ngon được, nhưng ví cũng cần sống.", 1),
        NativePlanTemplate("Chi tiêu ban đêm dễ bốc đồng hơn. Mình cân nhắc lại nhé.", 1),
        NativePlanTemplate("chi tiêu chạm giới hạn rồi. Từ giờ chỉ ưu tiên khoản cần.", 1),
        NativePlanTemplate("chi tiêu hơi nóng rồi. Chậm lại là vẫn cứu được.", 1),
        NativePlanTemplate("Cuối tháng gần tới rồi. Mình ưu tiên khoản cần thiết trước nhé.", 1),
        NativePlanTemplate("Di chuyển hôm nay hơi nhiều, mình cân lại phần còn lại nhé.", 1),
        NativePlanTemplate("Hôm nay chi tiêu xuất hiện hơi nhiều rồi.", 1),
        NativePlanTemplate("Hôm nay chưa tiêu linh tinh, giữ nhịp này nhé.", 1),
        NativePlanTemplate("Hôm nay ví đã đi qua vài giao dịch. Nghỉ một chút rồi mai tính tiếp.", 1),
        NativePlanTemplate("Một ly thì vui, nhiều ly thì ngân sách buồn.", 1),
        NativePlanTemplate("vài ngày kiểm soát tốt rồi. Đây là tiến bộ thật.", 1),
        NativePlanTemplate("Vượt hơi xa rồi. Nhưng dừng ngay thì vẫn kéo lại được.", 1),
        NativePlanTemplate("Bạn đang tạo một thói quen rất đáng giữ.", 2),
        NativePlanTemplate("Bữa này ổn, nhưng đừng để thành thói quen đắt đỏ.", 2),
        NativePlanTemplate("Cafe hôm nay đủ rồi, ví cần tỉnh theo.", 2),
        NativePlanTemplate("chi tiêu đang vượt kế hoạch. Hôm nay nên phòng thủ.", 2),
        NativePlanTemplate("Chuỗi tiết kiệm đang đẹp. Đừng phá nhịp nhé.", 2),
        NativePlanTemplate("Còn vài ngày, giữ nhịp một chút là qua tháng ổn.", 2),
        NativePlanTemplate("Đêm rồi, quyết định mua sắm nên để sáng mai tỉnh táo hơn.", 2),
        NativePlanTemplate("Dừng đúng lúc vẫn hơn sửa sai muộn.", 2),
        NativePlanTemplate("Giai đoạn cuối tháng nên phòng thủ nhẹ.", 2),
        NativePlanTemplate("Giảm một ly thôi là cuối tháng khác hẳn.", 2),
        NativePlanTemplate("Hôm nay ăn ngoài rồi, bữa sau cân lại nhé.", 2),
        NativePlanTemplate("Khoản đi lại đang cộng dồn. Theo dõi thêm chút sẽ tốt hơn.", 2),
        NativePlanTemplate("Khoản này có thể chờ tới sáng. Ví sẽ cảm ơn mình.", 2),
        NativePlanTemplate("Không chi không cần thiết là một chiến thắng nhỏ.", 2),
        NativePlanTemplate("Không sao, nhưng từ giờ mình cần nghiêm túc hơn.", 2),
        NativePlanTemplate("Mình đã chi chi tiêu vài lần hôm nay. Tạm dừng chút nhé.", 2),
        NativePlanTemplate("Mốc 80% tới rồi. Phanh sớm thì đỡ đau.", 2),
        NativePlanTemplate("Một lần nữa cho chi tiêu có thể làm ngân sách lệch nhịp.", 2),
        NativePlanTemplate("Một ngày yên bình cho ví. Rất đáng khen.", 2),
        NativePlanTemplate("Nếu có thể gộp chuyến, ví sẽ nhẹ hơn.", 2),
        NativePlanTemplate("Ngân sách mục này đã hết. Đừng tự làm khó cuối tháng.", 2),
        NativePlanTemplate("Ngày hôm nay xong rồi. Điều quan trọng là mình biết tiền đã đi đâu.", 2),
        NativePlanTemplate("Tổng kết nhẹ: hôm nay có vài khoản chi. Mình nhìn lại để ngày mai tốt hơn.", 2),
        NativePlanTemplate("Ví đang nhắc nhẹ: đừng để chi tiêu vượt kiểm soát.", 2),
        NativePlanTemplate("chi tiêu đã đủ rồi. Mình tạm khóa các khoản không cần nhé.", 3),
        NativePlanTemplate("chi tiêu đã dùng khoản đã chi/ngân sách. Từ giờ nên ưu tiên khoản cần.", 3),
        NativePlanTemplate("chi tiêu vượt 80%. Mình nên tạm giảm các khoản linh hoạt.", 3),
        NativePlanTemplate("Đừng để vài ngày cuối phá công sức cả tháng.", 3),
        NativePlanTemplate("Giảm một bữa gọi món là ngân sách nhẹ hơn nhiều.", 3),
        NativePlanTemplate("Một vài chuyến nhỏ cũng thành khoản đáng kể.", 3),
        NativePlanTemplate("Nếu chưa thật cần, mình để khoản này sang hôm khác nhé.", 3),
        NativePlanTemplate("Nếu không gấp, mình ngủ trước rồi quyết sau.", 3),
        NativePlanTemplate("Theo dõi được là đã hơn một nửa cuộc chơi.", 3),
        NativePlanTemplate("Thói quen nhỏ đang cộng thành khoản lớn.", 3),
        NativePlanTemplate("Ví hôm nay khỏe hơn hẳn.", 3),
        NativePlanTemplate("Ví ổn hơn nhờ những ngày như thế này.", 3),
        NativePlanTemplate("Ăn uống vui, nhưng nên có trần cho mỗi ngày.", 4),
        NativePlanTemplate("Ban đêm không phải lúc tốt nhất để ví ra quyết định.", 4),
        NativePlanTemplate("Còn ít ngày thôi, mình chi thật chọn lọc nhé.", 4),
        NativePlanTemplate("Đây là lúc ưu tiên kiểm soát thay vì thoải mái.", 4),
        NativePlanTemplate("Đi lại cần thiết, nhưng vẫn nên có giới hạn.", 4),
        NativePlanTemplate("Hôm nay chi tiêu đủ rồi, phần còn lại nên giữ.", 4),
        NativePlanTemplate("Không sao, nhưng từ giờ cần phòng thủ hơn.", 4),
        NativePlanTemplate("Mai chỉ cần tốt hơn hôm nay một chút là đủ.", 4),
        NativePlanTemplate("Một ngày kiểm soát tốt. Cứ thế tiếp tục.", 4),
        NativePlanTemplate("Tháng còn dài, mình giữ nhịp ở chi tiêu nhé.", 4),
        NativePlanTemplate("Tiết kiệm đều như vậy sẽ tạo khác biệt lớn.", 4),
        NativePlanTemplate("Tự pha vài hôm cũng là một cách giữ ví khỏe.", 4)
    )

    private val walletPet = listOf(
        NativePlanTemplate("Bụng vui rồi, giờ cho ví vui với nha.", 1),
        NativePlanTemplate("Cafe ngon nhưng ví bé run rồi nha.", 1),
        NativePlanTemplate("Còn vài ngày nữa, ví bé xin được sống sót.", 1),
        NativePlanTemplate("Đêm rồi mà ví bé vẫn phải làm việc á 🥹", 1),
        NativePlanTemplate("Hôm nay ví bé xử lý vài giao dịch, xin được nghỉ.", 1),
        NativePlanTemplate("Không chi linh tinh nè, ví bé thả tim.", 1),
        NativePlanTemplate("Lại chi tiêu nữa hả? Ví bé nhận ra pattern rồi nha.", 1),
        NativePlanTemplate("vài ngày ngoan với tiền, ví bé tự hào á.", 1),
        NativePlanTemplate("Ví bé đứng hình. chi tiêu full ngân sách rồi.", 1),
        NativePlanTemplate("Ví bé không khóc, ví bé chỉ tuyệt vọng nhẹ thôi 🥲", 1),
        NativePlanTemplate("Ví bé rén rồi, chi tiêu đã 80% á 🥹", 1),
        NativePlanTemplate("Ví bé vừa đi thêm một chuyến nữa.", 1),
        NativePlanTemplate("Cảnh báo xinh: chi tiêu sắp vượt mood an toàn.", 2),
        NativePlanTemplate("chi tiêu chạm nóc rồi á, cho ví nghỉ nha.", 2),
        NativePlanTemplate("chi tiêu nóng quá, ví bé cần quạt.", 2),
        NativePlanTemplate("chi tiêu vượt xa rồi, cứu ví với.", 2),
        NativePlanTemplate("Chuỗi đẹp quá, đừng làm ví bé hụt hẫng nha.", 2),
        NativePlanTemplate("Cuối tháng rồi, ví bé hơi nhạy cảm nha.", 2),
        NativePlanTemplate("Đi lại nhiều quá, ví bé hơi say xe.", 2),
        NativePlanTemplate("Đồ ăn ngon đó, nhưng ví bé hơi rén.", 2),
        NativePlanTemplate("Giao dịch đêm khuya làm ví bé giật mình.", 2),
        NativePlanTemplate("Hết slot cho chi tiêu. Ví bé xin đóng cửa.", 2),
        NativePlanTemplate("Hôm nay chi tiêu hơi được cưng chiều quá rồi đó.", 2),
        NativePlanTemplate("Hôm nay ví bé được nghỉ phép.", 2),
        NativePlanTemplate("Kết thúc ngày, ví bé cần sạc pin.", 2),
        NativePlanTemplate("Một ly nữa thôi là câu nói nguy hiểm nhất hôm nay.", 2),
        NativePlanTemplate("Thêm topping nữa là ví bé xỉu á.", 2),
        NativePlanTemplate("Tình hình hơi căng xinh rồi đó.", 2),
        NativePlanTemplate("Ví bé buồn ngủ rồi, đừng bắt ví thanh toán nữa.", 2),
        NativePlanTemplate("Ví bé cần bạn dịu tay vài ngày cuối.", 2),
        NativePlanTemplate("Ví bé đã làm việc chăm chỉ hôm nay rồi á.", 2),
        NativePlanTemplate("Ví bé đang thả tim vì chuỗi tiết kiệm này.", 2),
        NativePlanTemplate("Ví bé hỏi nhỏ: mình có thật sự cần thêm lần nữa không?", 2),
        NativePlanTemplate("Ví bé ngủ ngon vì bạn không tiêu bậy.", 2),
        NativePlanTemplate("Ví bé xin một bữa cơm nhà.", 2),
        NativePlanTemplate("Ví bé xin một ngày ít cuốc xe hơn.", 2),
        NativePlanTemplate("Bụng no, ví bé hơi rỗng.", 3),
        NativePlanTemplate("Hôm nay tiền đi hơi nhiều chưa ta? Ví bé đang suy nghĩ.", 3),
        NativePlanTemplate("Mỗi chuyến một ít, ví bé mất máu dần.", 3),
        NativePlanTemplate("Một ngày rất ngoan với tiền luôn á.", 3),
        NativePlanTemplate("Sắp qua tháng rồi, đừng làm ví bé khóc phút chót.", 3),
        NativePlanTemplate("Ví bé muốn được ôm sau con số 80%.", 3),
        NativePlanTemplate("Ví bé thấy chi tiêu xuất hiện hơi nhiều rồi á.", 3),
        NativePlanTemplate("Ví bé thấy tương lai sáng hơn một xíu rồi.", 3),
        NativePlanTemplate("Ví bé vừa thở dài rất sâu.", 3),
        NativePlanTemplate("Ví bé xin bạn bỏ topping hôm nay.", 3),
        NativePlanTemplate("Ví bé xin bạn đừng bấm thêm giao dịch chi tiêu nữa nha.", 3),
        NativePlanTemplate("Ví bé xin đi ngủ trước khi bạn chốt thêm.", 3),
        NativePlanTemplate("Bạn đang chăm ví bé rất tốt đó.", 4),
        NativePlanTemplate("chi tiêu đã full cây năng lượng xấu rồi 🥲", 4),
        NativePlanTemplate("chi tiêu đang làm ví bé tụt pin.", 4),
        NativePlanTemplate("chi tiêu làm ví bé mất ngủ rồi á.", 4),
        NativePlanTemplate("Đêm rồi, ví bé cần chăn chứ không cần hóa đơn.", 4),
        NativePlanTemplate("Ly này thơm, hóa đơn thì hơi đau.", 4),
        NativePlanTemplate("Món này ngon, nhưng ví bé muốn ăn cơm nhà.", 4),
        NativePlanTemplate("Thêm một lần nữa là ví bé dỗi đó nha.", 4),
        NativePlanTemplate("Ví bé chúc bạn ngủ ngon, đừng mơ thấy hóa đơn.", 4),
        NativePlanTemplate("Ví bé đang cười rất hiền.", 4),
        NativePlanTemplate("Ví bé đang đếm ngày về lương.", 4),
        NativePlanTemplate("Ví bé muốn được ở nhà hôm nay.", 4)
    )

    private val toxicFriend = listOf(
        NativePlanTemplate("Ăn ngoài nữa à? Bếp ở nhà chắc để làm cảnh.", 1),
        NativePlanTemplate("chi tiêu 100%. Chúc mừng, ngân sách đã bị xử đẹp.", 1),
        NativePlanTemplate("chi tiêu đã 80%. Kế hoạch tiết kiệm chắc để trưng.", 1),
        NativePlanTemplate("chi tiêu vượt 80%. Đây không còn là chi tiêu, đây là biểu diễn.", 1),
        NativePlanTemplate("Còn vài ngày. Đây là lúc ví cần sinh tồn, không cần phiêu lưu.", 1),
        NativePlanTemplate("Grab/be đang có vẻ thân với ví bạn quá.", 1),
        NativePlanTemplate("Hôm nay chưa tiêu linh tinh. Lạ nhưng đáng khen.", 1),
        NativePlanTemplate("Hôm nay có vài giao dịch. Ví đã chịu đựng rất chuyên nghiệp.", 1),
        NativePlanTemplate("Lại chi tiêu. Bạn rất chung thủy, tiếc là với việc tiêu tiền.", 1),
        NativePlanTemplate("Mua đồ lúc đêm: quyết định rất tỉnh táo, chắc vậy.", 1),
        NativePlanTemplate("vài ngày không phá ngân sách. Ai rồi cũng có lúc trưởng thành.", 1),
        NativePlanTemplate("Ví bạn đang tài trợ full cho caffeine.", 1),
        NativePlanTemplate("Bạn đang đầu tư mạnh vào niềm vui ngắn hạn.", 2),
        NativePlanTemplate("Câu 'mua nốt' đúng là câu đắt nhất tháng.", 2),
        NativePlanTemplate("chi tiêu đang tăng đẹp lắm. Đẹp theo kiểu báo động.", 2),
        NativePlanTemplate("Chuỗi này đẹp đấy, đừng để một cú chốt đơn phá hỏng.", 2),
        NativePlanTemplate("Cuối tháng rồi, đừng tạo plot twist tài chính nữa.", 2),
        NativePlanTemplate("Đêm khuya là lúc lý trí ngủ, còn ví thì chịu trận.", 2),
        NativePlanTemplate("Di chuyển kiểu này, ví cũng cần bản đồ sinh tồn.", 2),
        NativePlanTemplate("Giao dịch này có mùi bốc đồng lúc 2 giờ sáng.", 2),
        NativePlanTemplate("Gọi món nhanh hơn cả lúc hứa tiết kiệm.", 2),
        NativePlanTemplate("Hết ngân sách rồi. Phần còn lại chắc sống bằng niềm tin.", 2),
        NativePlanTemplate("Hôm nay chi tiêu xuất hiện hơi nhiều, chắc ví cũng quen bị tổn thương rồi.", 2),
        NativePlanTemplate("Không chi bậy hôm nay, cuối cùng lý trí cũng online.", 2),
        NativePlanTemplate("Mỗi chuyến nhỏ, tổng lại thì không nhỏ chút nào.", 2),
        NativePlanTemplate("Một lần nữa cho chi tiêu. Logic đã tạm nghỉ.", 2),
        NativePlanTemplate("Một ngày nữa ví sống sót. Khá đáng nể.", 2),
        NativePlanTemplate("Ngân sách đã ngã xuống, còn bạn vẫn chạy tiếp.", 2),
        NativePlanTemplate("Tỉnh thì có tỉnh, ngân sách thì ngủm.", 2),
        NativePlanTemplate("Tốc độ này mà gọi là kiểm soát thì cũng lạc quan đấy.", 2),
        NativePlanTemplate("Tổng kết ngày: tiền đi, bài học ở lại.", 2),
        NativePlanTemplate("Trà sữa không đắt. Đắt là cái thói 'ly cuối'.", 2),
        NativePlanTemplate("Vài ngày cuối mà tiêu bốc đồng là phim có kết buồn.", 2),
        NativePlanTemplate("Ví chưa bị tổn thương mấy ngày rồi. Lạ nhưng tốt.", 2),
        NativePlanTemplate("Ví còn sống khỏe. Một diễn biến hiếm gặp.", 2),
        NativePlanTemplate("Vượt thế này cuối tháng khỏi bất ngờ.", 2),
        NativePlanTemplate("Ăn ngon hôm nay, cuối tháng ăn năn.", 3),
        NativePlanTemplate("Bạn không đi lại, bạn đang tài trợ giao thông cá nhân.", 3),
        NativePlanTemplate("chi tiêu đã chạm trần. Plot twist cuối tháng đang tới.", 3),
        NativePlanTemplate("chi tiêu đang đi đúng lộ trình: lộ trình áp lực.", 3),
        NativePlanTemplate("chi tiêu hôm nay lên sóng nhiều hơn cả deadline.", 3),
        NativePlanTemplate("Hôm nay ngân sách có drama hay không thì bạn tự biết.", 3),
        NativePlanTemplate("Lý trí đang thắng. Hiếm, nên giữ.", 3),
        NativePlanTemplate("Mới vậy đã khoản đã chi/ngân sách. Ví chắc quen bị tổn thương rồi.", 3),
        NativePlanTemplate("Một ly nhỏ, một vấn đề cộng dồn lớn.", 3),
        NativePlanTemplate("Một ngày không làm ví tổn thương. Tiến bộ đấy.", 3),
        NativePlanTemplate("Ngân sách đã mệt, đừng bắt nó chạy marathon.", 3),
        NativePlanTemplate("Sáng mai bạn sẽ hiểu vì sao ví im lặng.", 3),
        NativePlanTemplate("Bạn đang biến ngân sách thành nội dung giải trí.", 4),
        NativePlanTemplate("Bạn đang cư xử như người có kế hoạch. Bất ngờ đấy.", 4),
        NativePlanTemplate("Bạn với chi tiêu đúng là một mối quan hệ tốn kém.", 4),
        NativePlanTemplate("Caffeine cứu bạn, nhưng ai cứu ví?", 4),
        NativePlanTemplate("Câu 'mua nốt' bắt đầu có mùi đắt đỏ rồi đó.", 4),
        NativePlanTemplate("Còn ít ngày thôi, đừng biến tháng này thành bài học đắt tiền.", 4),
        NativePlanTemplate("Đồ ăn tới nhanh, số dư đi cũng nhanh.", 4),
        NativePlanTemplate("Hôm nay ngân sách không bị drama. Khá hiếm.", 4),
        NativePlanTemplate("Một cú chi tiêu rất hợp vibe mất kiểm soát.", 4),
        NativePlanTemplate("Ngân sách vừa rời khỏi cuộc trò chuyện.", 4),
        NativePlanTemplate("Ví không nói gì, nhưng lịch sử giao dịch nói khá nhiều.", 4),
        NativePlanTemplate("Ví vừa book thêm một vé áp lực cuối tháng.", 4)
    )

    private val vietnameseParentSoft = listOf(
        NativePlanTemplate("Bếp ở nhà để trưng à?", 1),
        NativePlanTemplate("Cắt bớt cafe ngoài quán ngay.", 1),
        NativePlanTemplate("chi tiêu đã 80% rồi. Bớt tiêu theo hứng ngay.", 1),
        NativePlanTemplate("chi tiêu hết ngân sách rồi. Dừng.", 1),
        NativePlanTemplate("Cuối tháng rồi, giữ tiền lại.", 1),
        NativePlanTemplate("Đêm hôm còn tiêu tiền. Đi ngủ đi.", 1),
        NativePlanTemplate("Đi lại nhiều quá rồi, tính lại đi.", 1),
        NativePlanTemplate("Hôm nay không tiêu linh tinh, thế mới giống người biết nghĩ.", 1),
        NativePlanTemplate("Hôm nay tiêu thế nào thì tự nhìn lại đi.", 1),
        NativePlanTemplate("Lại chi tiêu? Tiền mọc trên cây à?", 1),
        NativePlanTemplate("vài ngày giữ được tiền. Tốt, tiếp tục.", 1),
        NativePlanTemplate("Vượt 80% rồi. Dừng ngay.", 1),
        NativePlanTemplate("100% rồi mà còn tiêu nữa thì cuối tháng tự chịu.", 2),
        NativePlanTemplate("Ăn ngoài ít thôi. Ví không chịu nổi đâu.", 2),
        NativePlanTemplate("Còn vài ngày nữa, đừng tiêu bậy.", 2),
        NativePlanTemplate("Cuốc nào không cần thì bớt.", 2),
        NativePlanTemplate("Cuối ngày rồi, xem lại tiền đi đâu.", 2),
        NativePlanTemplate("Đấy, biết nghĩ thì vẫn làm được.", 2),
        NativePlanTemplate("Để sáng mai tỉnh táo rồi tính.", 2),
        NativePlanTemplate("Dừng cái kiểu thích là mua lại ngay.", 2),
        NativePlanTemplate("Đừng có 'ly cuối', câu đấy nghe nhiều rồi.", 2),
        NativePlanTemplate("Đừng lấy lý do stress để đốt tiền ăn uống.", 2),
        NativePlanTemplate("Đừng viện cớ nữa. Mục này hết tiền rồi.", 2),
        NativePlanTemplate("Giờ này mà còn mua với bán gì nữa?", 2),
        NativePlanTemplate("Giữ được như hôm nay thì ví mới sống nổi.", 2),
        NativePlanTemplate("Giữ như này thì cuối tháng mới đỡ khổ.", 2),
        NativePlanTemplate("Khóa chi linh tinh ngay. Không thương lượng.", 2),
        NativePlanTemplate("Nhìn lại đi, chi tiêu đang cháy ngân sách đấy.", 2),
        NativePlanTemplate("Sắp hết tháng rồi mà còn vung tay là tự chịu.", 2),
        NativePlanTemplate("Tiền xe cũng là tiền, đừng coi nhẹ.", 2),
        NativePlanTemplate("Tốt. Mai cũng đừng phá.", 2),
        NativePlanTemplate("Từ giờ khoản nào không cần thì cắt.", 2),
        NativePlanTemplate("Uống ít lại. Tiền không tự mọc lại đâu.", 2),
        NativePlanTemplate("vài giao dịch rồi đấy, mai bớt lại.", 2),
        NativePlanTemplate("Biết ghi lại là tốt, nhưng phải biết sửa nữa.", 3),
        NativePlanTemplate("chi tiêu đủ rồi. Đừng thêm nữa.", 3),
        NativePlanTemplate("chi tiêu dùng khoản đã chi/ngân sách rồi. Đừng có chủ quan.", 3),
        NativePlanTemplate("Cơm nhà không có tội.", 3),
        NativePlanTemplate("Đừng chủ quan rồi phá chuỗi.", 3),
        NativePlanTemplate("Đừng có thức khuya rồi tiêu linh tinh.", 3),
        NativePlanTemplate("Đừng tiêu kiểu này nữa, cuối tháng khổ là tự chịu.", 3),
        NativePlanTemplate("Gộp việc lại rồi đi một lần thôi.", 3),
        NativePlanTemplate("Khoản nào không cần thì cắt hết.", 3),
        NativePlanTemplate("Không tiêu bậy là đúng, không phải thành tích để chủ quan.", 3),
        NativePlanTemplate("Từ giờ không có 'nốt lần này'.", 3),
        NativePlanTemplate("Tự pha ở nhà đi.", 3),
        NativePlanTemplate("Ăn uống kiểu này thì tiền nào cho đủ.", 4),
        NativePlanTemplate("Cả ngày cứ chi tiêu, ví nào chịu nổi.", 4),
        NativePlanTemplate("Đừng để mẹ ví phải mắng thêm lần nữa.", 4),
        NativePlanTemplate("Hết là hết. Không thương lượng.", 4),
        NativePlanTemplate("Hôm nay ổn. Cứ thế mà làm.", 4),
        NativePlanTemplate("Không phải cứ lười là gọi xe.", 4),
        NativePlanTemplate("Mai tiêu có nghĩ hơn hôm nay.", 4),
        NativePlanTemplate("Mấy ngày cuối phải biết giữ ví.", 4),
        NativePlanTemplate("Ngày nào cũng cafe thì ví nào chịu.", 4),
        NativePlanTemplate("Ngủ đi, ví cũng cần nghỉ.", 4),
        NativePlanTemplate("Tốt. Tiền phải giữ từ những ngày như này.", 4)
    )

    private val vietnameseParentStrong = listOf(
        NativePlanTemplate("Bếp ở nhà để trưng à?", 1),
        NativePlanTemplate("Cắt bớt cafe ngoài quán ngay.", 1),
        NativePlanTemplate("chi tiêu đã 80% rồi. Bớt tiêu theo hứng ngay.", 1),
        NativePlanTemplate("chi tiêu hết ngân sách rồi. Dừng.", 1),
        NativePlanTemplate("Cuối tháng rồi, giữ tiền lại.", 1),
        NativePlanTemplate("Đêm hôm còn tiêu tiền. Đi ngủ đi.", 1),
        NativePlanTemplate("Đi lại nhiều quá rồi, tính lại đi.", 1),
        NativePlanTemplate("Hôm nay không tiêu linh tinh, thế mới giống người biết nghĩ.", 1),
        NativePlanTemplate("Hôm nay tiêu thế nào thì tự nhìn lại đi.", 1),
        NativePlanTemplate("Lại chi tiêu? Tiền mọc trên cây à?", 1),
        NativePlanTemplate("vài ngày giữ được tiền. Tốt, tiếp tục.", 1),
        NativePlanTemplate("Vượt 80% rồi. Dừng ngay.", 1),
        NativePlanTemplate("100% rồi mà còn tiêu nữa thì cuối tháng tự chịu.", 2),
        NativePlanTemplate("Ăn ngoài ít thôi. Ví không chịu nổi đâu.", 2),
        NativePlanTemplate("chi tiêu vượt quá xa rồi, mày đang tự phá kế hoạch.", 2),
        NativePlanTemplate("Còn vài ngày nữa, đừng tiêu bậy.", 2),
        NativePlanTemplate("Cuốc nào không cần thì bớt.", 2),
        NativePlanTemplate("Cuối ngày rồi, xem lại tiền đi đâu.", 2),
        NativePlanTemplate("Đấy, biết nghĩ thì vẫn làm được.", 2),
        NativePlanTemplate("Để sáng mai tỉnh táo rồi tính.", 2),
        NativePlanTemplate("Dừng cái kiểu thích là mua lại ngay.", 2),
        NativePlanTemplate("Đừng có 'ly cuối', câu đấy nghe nhiều rồi.", 2),
        NativePlanTemplate("Đừng lấy lý do stress để đốt tiền ăn uống.", 2),
        NativePlanTemplate("Đừng viện cớ nữa. Mục này hết tiền rồi.", 2),
        NativePlanTemplate("Giờ này mà còn mua với bán gì nữa?", 2),
        NativePlanTemplate("Giữ được như hôm nay thì ví mới sống nổi.", 2),
        NativePlanTemplate("Giữ như này thì cuối tháng mới đỡ khổ.", 2),
        NativePlanTemplate("Hôm nay mày chi chi tiêu hơi nhiều rồi đấy.", 2),
        NativePlanTemplate("Khóa chi linh tinh ngay. Không thương lượng.", 2),
        NativePlanTemplate("Nhìn lại đi, chi tiêu đang cháy ngân sách đấy.", 2),
        NativePlanTemplate("Sắp hết tháng rồi mà còn vung tay là tự chịu.", 2),
        NativePlanTemplate("Tiền xe cũng là tiền, đừng coi nhẹ.", 2),
        NativePlanTemplate("Tốt. Mai cũng đừng phá.", 2),
        NativePlanTemplate("Từ giờ khoản nào không cần thì cắt.", 2),
        NativePlanTemplate("Uống ít lại. Tiền không tự mọc lại đâu.", 2),
        NativePlanTemplate("vài giao dịch rồi đấy, mai bớt lại.", 2),
        NativePlanTemplate("Biết ghi lại là tốt, nhưng phải biết sửa nữa.", 3),
        NativePlanTemplate("chi tiêu đủ rồi. Đừng thêm nữa.", 3),
        NativePlanTemplate("chi tiêu dùng khoản đã chi/ngân sách rồi. Đừng có chủ quan.", 3),
        NativePlanTemplate("Cơm nhà không có tội.", 3),
        NativePlanTemplate("Đừng chủ quan rồi phá chuỗi.", 3),
        NativePlanTemplate("Đừng có thức khuya rồi tiêu linh tinh.", 3),
        NativePlanTemplate("Đừng tiêu kiểu này nữa, cuối tháng khổ là tự chịu.", 3),
        NativePlanTemplate("Gộp việc lại rồi đi một lần thôi.", 3),
        NativePlanTemplate("Khoản nào không cần thì cắt hết.", 3),
        NativePlanTemplate("Không tiêu bậy là đúng, không phải thành tích để chủ quan.", 3),
        NativePlanTemplate("Từ giờ không có 'nốt lần này'.", 3),
        NativePlanTemplate("Tự pha ở nhà đi.", 3),
        NativePlanTemplate("Ăn uống kiểu này thì tiền nào cho đủ.", 4),
        NativePlanTemplate("Cả ngày cứ chi tiêu, ví nào chịu nổi.", 4),
        NativePlanTemplate("Đừng để mẹ ví phải mắng thêm lần nữa.", 4),
        NativePlanTemplate("Hết là hết. Không thương lượng.", 4),
        NativePlanTemplate("Hôm nay ổn. Cứ thế mà làm.", 4),
        NativePlanTemplate("Không phải cứ lười là gọi xe.", 4),
        NativePlanTemplate("Mai tiêu có nghĩ hơn hôm nay.", 4),
        NativePlanTemplate("Mấy ngày cuối phải biết giữ ví.", 4),
        NativePlanTemplate("Ngày nào cũng cafe thì ví nào chịu.", 4),
        NativePlanTemplate("Ngủ đi, ví cũng cần nghỉ.", 4),
        NativePlanTemplate("Tao nói thẳng: mục này phải phanh lại ngay.", 4),
        NativePlanTemplate("Tốt. Tiền phải giữ từ những ngày như này.", 4)
    )

    fun pick(toneMode: String, allowStrongLanguage: Boolean, tier: Int): String {
        val pool = when (toneMode) {
            "gentle", "advisor" -> advisor
            "cute", "wallet_pet" -> walletPet
            "sarcastic_strong", "toxic_friend" -> toxicFriend
            "angry", "strict", "vietnamese_parent" -> if (allowStrongLanguage) vietnameseParentStrong else vietnameseParentSoft
            else -> advisor
        }
        if (pool.isEmpty()) {
            return PeriodicFallbackTemplates.pick(toneMode, allowStrongLanguage, tier)
        }
        val tierPool = pool.filter { kotlin.math.abs(it.tier - tier) <= 1 }.ifEmpty { pool }
        return tierPool[Random.nextInt(tierPool.size)].body
    }
}
