// Auto-generated by scripts/with-env.js. Do not edit manually.
export const RUNTIME_ENV = {
  GEMINI_API_KEY: "AIzaSyCFokHt7NOQsMnKrj3Ea5B0oSX__KVK1O4",
  GOOGLE_API_KEY: "",
  OPENAI_API_KEY: "",
  PAYNOTE_AI_PROVIDER: "",
  PAYNOTE_AI_API_KEY: "",
  PAYNOTE_AI_MODEL: "",
  PAYNOTE_AI_TIMEOUT_MS: "",
} as const;
