#!/usr/bin/env node
/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');
const {spawn} = require('child_process');

const projectRoot = process.cwd();
const envPath = path.join(projectRoot, '.env');
const generatedEnvPath = path.join(projectRoot, 'src', 'config', 'runtimeEnv.generated.ts');

const parseEnvFile = (content) => {
  const env = {};
  content.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return;
    }
    const idx = trimmed.indexOf('=');
    if (idx <= 0) {
      return;
    }
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  });
  return env;
};

const loadDotEnv = () => {
  if (!fs.existsSync(envPath)) {
    return {};
  }
  try {
    const raw = fs.readFileSync(envPath, 'utf8');
    return parseEnvFile(raw);
  } catch (error) {
    console.warn('[with-env] Failed to read .env:', error);
    return {};
  }
};

const writeGeneratedEnvModule = (env) => {
  const safe = {
    GEMINI_API_KEY: typeof env.GEMINI_API_KEY === 'string' ? env.GEMINI_API_KEY : '',
    GOOGLE_API_KEY: typeof env.GOOGLE_API_KEY === 'string' ? env.GOOGLE_API_KEY : '',
  };
  const content = [
    '// Auto-generated by scripts/with-env.js. Do not edit manually.',
    'export const RUNTIME_ENV = {',
    `  GEMINI_API_KEY: ${JSON.stringify(safe.GEMINI_API_KEY)},`,
    `  GOOGLE_API_KEY: ${JSON.stringify(safe.GOOGLE_API_KEY)},`,
    '} as const;',
    '',
  ].join('\n');
  fs.writeFileSync(generatedEnvPath, content, 'utf8');
};

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('[with-env] Missing command. Example: node scripts/with-env.js react-native start');
  process.exit(1);
}

const fileEnv = loadDotEnv();
writeGeneratedEnvModule(fileEnv);
const mergedEnv = {...process.env, ...fileEnv};

const child = spawn(args[0], args.slice(1), {
  stdio: 'inherit',
  shell: true,
  env: mergedEnv,
});

child.on('exit', (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }
  process.exit(code ?? 1);
});
